### ISSUE TITLE
Tracking: JS SDK (Group Chat - Web)

### ISSUE THREAD

**Issue by nplasterer** [xmtp/xmtp-web#250]
### Group Chat

Should mimic functionality found for groups in iOS, Android, and RN.

- [ ] xmtp/xmtp-js#556
  - [ ] Client
    - [ ] xmtp/xmtp-js#557
    - [ ] xmtp/xmtp-js#558
    - [ ] xmtp/xmtp-js#559
    - [ ] xmtp/xmtp-js#560
    - [ ] xmtp/xmtp-js#561
    - [ ] xmtp/xmtp-js#562
    - [ ] xmtp/xmtp-js#563
    - [ ] xmtp/xmtp-js#564
    - [ ] xmtp/xmtp-js#565
  - [ ] Conversations
    - [ ] xmtp/xmtp-js#566
    - [ ] xmtp/xmtp-js#567
    - [ ] xmtp/xmtp-js#568
    - [ ] xmtp/xmtp-js#569
    - [ ] xmtp/xmtp-js#570
    - [ ] xmtp/xmtp-js#571
    - [ ] xmtp/xmtp-js#572
  - [ ] Conversation/Group methods
    - [ ] xmtp/xmtp-js#573
    - [ ] xmtp/xmtp-js#574
    - [ ] xmtp/xmtp-js#575
    - [ ] xmtp/xmtp-js#576
    - [ ] xmtp/xmtp-js#577
    - [ ] xmtp/xmtp-js#578
    - [ ] xmtp/xmtp-js#579
    - [ ] xmtp/xmtp-js#580
    - [ ] xmtp/xmtp-js#581
    - [ ] xmtp/xmtp-js#582
    - [ ] xmtp/xmtp-js#583
    - [ ] xmtp/xmtp-js#584
    - [ ] xmtp/xmtp-js#585
    - [ ] xmtp/xmtp-js#586
    - [ ] xmtp/xmtp-js#587

### Nice to have

- [ ] Create sample app
    - [ ] Use SDK to demonstrate
        - [ ] Group Chat
          - [ ] send messages (any content type)
          - [ ] add member
          - [ ] remove member
          - [ ] list members
          - [ ] leave
